# vim:ft=ansible:
---

- name: install neovim
  become: true
  package:
    name: neovim
    state: present

- name: create neovim config path
  file:
    dest: "{{ ansible_env.HOME }}/.config/nvim/autoload"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"

- name: create neovim bundle path
  file:
    dest: "{{ ansible_env.HOME }}/.nvim/bundle"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"

- name: intall neovim plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME  }}/.config/nvim/autoload/plug.vim"
    mode: 0644

- name: install neovim config
  copy:
    src: roles/common/files/nvim
    dest: "{{ ansible_env.HOME }}/.config/"
    directory_mode: yes
    follow: no
    mode: 0644
    owner: "{{ ansible_user }}"





