# vim:ft=ansible:
---

- name: install vim
  become: true
  package:
    name: vim
    state: present

- name: install vimrc
  template:
    src: templates/vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: 0644
    owner: "{{ ansible_user }}"

