# vim:ft=ansible:
---

- name: create bin path
  file:
    dest: "{{ ansible_env.HOME }}/bin/"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"

- name: install to
  copy:
    src: roles/development/files/to
    dest: "{{ ansible_env.HOME }}/bin/to"
    mode: 0744
    owner: "{{ ansible_user }}"

- name: create ssh config path
  file:
    dest: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"

- name: install ssh config
  copy:
    src: roles/development/files/ssh_config
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: 0644
    owner: "{{ ansible_user }}"

- name: install ideavimrc
  copy:
    src: roles/development/files/ideavimrc
    dest: "{{ ansible_env.HOME }}/.ideavimrc"
    mode: 0644
    owner: "{{ ansible_user }}"

- name: install gencert
  copy:
    src: roles/development/files/gencert.sh
    dest: "{{ ansible_env.HOME }}/bin/gencert.sh"
    mode: 0744
    owner: "{{ ansible_user }}"

- name: install delete merged branch script
  copy:
    src: roles/development/files/delete_merged_branchs
    dest: "{{ ansible_env.HOME }}/bin/delete_merged_branchs"
    mode: 0744
    owner: "{{ ansible_user }}"
