# vim:ft=ansible:
---

- name: create bin path
  file:
    dest: "{{ ansible_env.HOME }}/bin/"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"

- name: install to
  copy:
    src: files/to
    dest: "{{ ansible_env.HOME }}/bin/to"
    mode: 0744
    owner: "{{ ansible_user }}"

- name: create ssh config path
  file:
    dest: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"

- name: install ssh config
  copy:
    src: files/ssh_config
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: 0644
    owner: "{{ ansible_user }}"

- name: install tmux config
  copy:
    src: files/tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    mode: 0644
    owner: "{{ ansible_user }}"

- name: install tmux init script
  copy:
    src: files/tmuxinit
    dest: "{{ ansible_env.HOME }}/bin/tmuxinit"
    mode: 0644
    owner: "{{ ansible_user }}"

- name: install ideavimrc
  copy:
    src: files/ideavimrc
    dest: "{{ ansible_env.HOME }}/.ideavimrc"
    mode: 0644
    owner: "{{ ansible_user }}"

- name: install gencert
  copy:
    src: files/gencert.sh
    dest: "{{ ansible_env.HOME }}/bin/gencert.sh"
    mode: 0744
    owner: "{{ ansible_user }}"

