#!/usr/bin/expect -f

set timeout 10

set DEFAULT_PORT 36000
set DEFAULT_USER qqpet
set DEFAULT_PASS freshpet_0602
set pass [exec sh -c "echo -n \$SSH_PASS"]

set host [lindex $argv 0]
set user [lindex $argv 1]
set port [lindex $argv 2]

if { ($host == "") } {
    puts "usage: jkssh <host> \[user\] \[port\]"
    puts "default port=$DEFAULT_PORT"
    puts "default user=$DEFAULT_USER"
    puts "put passwd to env SSH_PASS"
    return -1;
}

if { ($port == "") } {
    set port $DEFAULT_PORT
}

if { ($user == "") } {
    set user $DEFAULT_USER
}

if { ($pass == "") } {
    set pass $DEFAULT_PASS
}

spawn ssh -p $port -l $user $host
expect {
    "Interrupted system call" {
        spawn strace -o /dev/null ssh -p$port -l $user $host
        expect {
            "*assword:" {
                send "$pass\r"
            }
            "(yes/no)?" {
                send "yes\r"
                expect "*assword:"
                send "$pass\r"
            }
        }
    }
    "*assword:" {
        send "$pass\r"
    }
    "(yes/no)?" {
        send "yes\r"
        expect "*assword:"
        send "$pass\r"
    }
}

#expect eof
interact

