#! /bin/sh

HOST_PATH="hosts"
DEFAULT_USER="youdonghai"
DEFAULT_PORT=22

ALL_HOST=`ls ${HOME}/${HOST_PATH}/* | awk -F/ '{print $NF}' |  tr "\n" "|"`

if [ -z "$1" ];then
    tmux setw automatic-rename > /dev/null 2>&1
    echo "usage: to <host> [user] [passwd] [port]"
    echo "       to <host_type> <host_index>"
    echo "default user=${DEFAULT_USER}"
    echo "default port=${DEFAULT_PORT}"
    exit 0
fi

HOST_TYPE="$1"
echo ${ALL_HOST} | grep -w "${HOST_TYPE}" > /dev/null
if [ $? -eq 0 ];then
    SSH_INDEX="$2"
    if [ -z "${SSH_INDEX}" ];then
        SSH_INDEX="1"
    fi
    SSH_INDEX=$((SSH_INDEX+1))
    SSH_HOST="$(cat ${HOME}/${HOST_PATH}/${HOST_TYPE}|head -n ${SSH_INDEX}|tail -n 1|awk -F\| '{print $1}')"
    SSH_USER="$(cat ${HOME}/${HOST_PATH}/${HOST_TYPE}|head -n ${SSH_INDEX}|tail -n 1|awk -F\| '{print $2}')"
    SSH_PASS="$(cat ${HOME}/${HOST_PATH}/${HOST_TYPE}|head -n ${SSH_INDEX}|tail -n 1|awk -F\| '{print $3}')"
    SSH_PORT="$(cat ${HOME}/${HOST_PATH}/${HOST_TYPE}|head -n ${SSH_INDEX}|tail -n 1|awk -F\| '{print $4}')"
else
    SSH_HOST=${HOST_TYPE}
    SSH_USER=$2
    SSH_PASS=$3
    SSH_PORT=$4
fi

if [ -z "${SSH_PORT}" ];then
    SSH_PORT=${DEFAULT_PORT}
fi
if [ -z "${SSH_USER}" ];then
    SSH_USER=${DEFAULT_USER}
fi

tmux rename-window ${SSH_HOST} > /dev/null 2>&1
if [ -z "${SSH_PASS}" ];then
    ssh -p ${SSH_PORT} -l ${SSH_USER} ${SSH_HOST}
else
    export SSHPASS=${SSH_PASS}
    sshpass -e ssh -p ${SSH_PORT} -l ${SSH_USER} ${SSH_HOST}
fi
tmux setw automatic-rename > /dev/null 2>&1

