# vim:ft=ansible:
---
- include: zsh.yaml

- name: create bin path
  file:
    dest: "{{ ansible_env.HOME }}/bin/"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"

- name: install to
  copy:
    src: files/to
    dest: "{{ ansible_env.HOME }}/bin/to"
    mode: 0744
    owner: "{{ ansible_user }}"

- name: install ssh config
  copy:
    src: files/ssh_config
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: 0644
    owner: "{{ ansible_user }}"

- name: install tmux config
  copy:
    src: files/tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    mode: 0644
    owner: "{{ ansible_user }}"

- name: install ideavimrc
  copy:
    src: files/ideavimrc
    dest: "{{ ansible_env.HOME }}/.ideavimrc"
    mode: 0644
    owner: "{{ ansible_user }}"

- name: debug vars
  debug:
    msg: "{{ VIM_USE_YCM }}"

- name: install vimrc
  template:
    src: templates/vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: 0644
    owner: "{{ ansible_user }}"

- name: install gencert
  copy:
    src: files/gencert.sh
    dest: "{{ ansible_env.HOME }}/bin/gencert.sh"
    mode: 0744
    owner: "{{ ansible_user }}"

